#Config version (do not update)
version: "1.1.0"

#Bot token
token: "insert token here"

#Default server
default_server: "lobby"

#Channels IDS in discord for the following chat channels.
chat:
  global:
  support:
    info:
    chat:
  staff:

#Chat Socket Port
socket_port: 30589

#Network messages
#%player% is a placeholder for the player name.
custom_messages:
  enabled: true
  leave: '%player% has left UKnet'

#Message ID in discord.
message:
  reviewer:

#Reviewer role id.
role:
  reviewer:

#Database login
host: localhost
port: 3306
username: root
password: password

#Database names (doesn't require adjusting)
database:
  global: uknet_global
  plot: uknet_plots
  region: uknet_regions

#Progress map link
progress_map: https://maphub.net/BTEItaliaLocals/bte-uk-progress-map
