#Config version (do not update)
version: "1.8.0"

#Bot token
token: "insert token here"

#Default server
default_server: "lobby"

#Channels IDS in discord for the following chat channels.
chat:
  global: 0
  support:
    info: 0
    chat: 0
  staff: 0

#Discord role IDs.
discord_roles:
  default: 0
  applicant: 0
  apprentice: 0
  jrbuilder: 0
  builder: 0
  architect: 0
  reviewer: 0

#Chat Socket Port
socket_port: 30589

#Network messages
#%player% is a placeholder for the player name.
custom_messages:
  enabled: true
  leave: '%player% has left UKnet'

#Message ID in discord.
message:
  reviewer:

#Reviewer role id.
role:
  reviewer:

#Role syncing will give all users with any of the 'has' roles the 'give' roles.
#Roles must be the role id.
role_syncing:
  has: []
  give: []


#Database login
host: localhost
port: 3306
username: root
password: password

#Database names (doesn't require adjusting)
database:
  global: uknet_global
  plot: uknet_plots
  region: uknet_regions

#Progress map link
progress_map: https://maphub.net/BTEItaliaLocals/bte-uk-progress-map
