#Config version (do not change!)
version: 1.0.0

#Bot token
token: "insert token here"

#Channels IDS in discord for the following chat channels.
chat:
  global:
  reviewer:
  staff:

#Chat socket port.
socket_port: 30589

#Message ID in discord.
message:
  reviewer:

#Database login
host: localhost
port: 3306
username: root
password: password

#Database names (doesn't require adjusting)
database:
  global: uknet_global
  plot: uknet_plots
